### ISSUE TITLE
v7.0.0 ロードマップ

### ISSUE THREAD

**Issue by sya-ri** [sya-ri/HAL_Extension#18]
# バグ修正
- [x] エンコーダーの値が飛ぶ #19 by @alcedo-taku

# 機能
## クラスの追加

- [x] CAN #20 by @alcedo-taku, @sya-ri 
- [x] Button #31  by @alcedo-taku
  - チャタリング防止
- [x] BooleanStateButton #31 by @alcedo-taku
  - 1回押すとONになり、もう1回押すとOFFになる。

## 機能追加
- [x] #4 by @sya-ri 
- [x] #5 by @sya-ri 

## パフォーマンス改善
- [ ] ~~可能な限りの関数のインライン化~~ by @sya-ri

## 機能削除

- [x] コールバック関数が自動で定義されてしまわないようにする #24 by @sya-ri
- [ ] ~~const, noexcept を削除する~~ by @sya-ri
      - 定義が分かりにくくなるだけであり、マイコン環境で例外を扱うことはないので不要

# ドキュメント
- [ ] ~~Writerside を使って書き直す~~ by @sya-ri
      - #6 も対応したい

# 全体的な変更
- [x] バージョン対応を C++17 にする by @sya-ri 
- [x] defineを使ったモジュール無効化の削除 #26 by @sya-ri
  - has_include によって自動判別する
  - CONFIG_DISABLE_IWDG_CONSTEXPR を削除 #25 by @sya-ri 
- [x] ライセンスの追加 by @sya-ri

**Comment by sya-ri** [comment]
一部対応しないこととして v7.0.0 をリリース
